services:
  identifier:
    image: semtech/mu-identifier:1.10.3
    environment:
      SESSION_COOKIE_SECURE: "on"
    labels:
      - "logging=true"
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"

  # Your extra services here

  resource:
    image: semtech/mu-cl-resources:1.25.0
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"

  migrations:
    image: semtech/mu-migrations-service:0.9.0
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
  delta-notifier:
    image: semtech/mu-delta-notifier:0.4.0
    volumes:
      - ./config/delta:/config/
    labels:
      - "logging=true"
  database:
    image: semtech/sparql-parser:0.0.8
    volumes:
      - ./config/authorization/:/config/
      - ./data/authorization/:/data/
    labels:
      - "logging=true"
  triplestore:
    image: redpencil/virtuoso:1.2.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
  file:
    image: semtech/mu-file-service:3.4.0
    links:
      - database:database
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
  custom-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
    ports:
      - 8888:80
    volumes:
      - ./services/custom-service/:/app/
    labels:
      - "logging=true"